### ISSUE TITLE
Add content to "good code reviewing practices" chapter

### ISSUE THREAD

**Issue by BScheliga** [AbdnCHDS/guidebook#11]
This is a document that explains how to roughly structure and comment your comment. As well as how to review the code of others.

I just remembered I already created a draft for an Rmarkdown template [https://github.com/AbdnCHDS/guidebook/blob/master/R/Template_Bernhard_R_Notebook.Rmd](https://github.com/AbdnCHDS/guidebook/blob/master/R/Template_Bernhard_R_Notebook.Rmd)

Still should put things into writing.

resource: https://code.joejag.com/2021/tech-test-marking-guide.html

**Comment by dblana** [comment]
Combined with good coding practices chapter
