### ISSUE TITLE
Add content to "collaboration" chapter

### ISSUE THREAD

**Issue by ClaraGlocke** [AbdnCHDS/guidebook#15]
•	Use of Github to host projects, enable peer review and track team contributions.

**Comment by dblana** [comment]
* Why GitHub?
* Summarise the GitHub workflow (this is explained in the [Contributor Guidelines in the Readme file](https://github.com/AbdnCHDS/guidebook/blob/master/README.md#contributor-guidelines), and also on [GitHub Docs](https://docs.github.com/en/get-started/quickstart/github-flow))
* Mention [GitHub Desktop](https://desktop.github.com/) as an easy way to interact with GitHub on your local computer

**Comment by dblana** [comment]
Combined with good coding practices chapter
