### ISSUE TITLE
See if you can add Snafu video to documentation chapter

### ISSUE THREAD

**Issue by ClaraGlocke** [AbdnCHDS/guidebook#25]

**Comment by ClaraGlocke** [comment]
Tried to embed using html.  Cannot find a way to see if it has worked.
If it doesn't there are other options using Imgur.  See:  https://stackoverflow.com/questions/11804820/how-can-i-embed-a-youtube-video-on-github-wiki-pages

**Comment by dblana** [comment]
Done: https://github.com/AbdnCHDS/guidebook/blob/master/pages/data-documentation.md
