### ISSUE TITLE
R notebook - template file?

### ISSUE THREAD

**Issue by BScheliga** [AbdnCHDS/guidebook#3]
@dblana, @JessButler  Do you reckon it makes sense to create some sort of  R notebook template file for the centre? 

That provides a frame for R-scripts and forces some form of consistency across the R-scripts. Nothing much, but just to give people a starting point. 

e.g. 

---
title: "R Notebook for ???"
author: [Enter Your Name]
  date: YYYY-MM-DD
output: pdf_document
---
Data set created by  
Author: [*Enter Your Name*]
```{r echo=FALSE}
#Enter the Version of the data set here, if applicable. Or else delete
Dataset_version <- "0.2"
```
```{r echo=FALSE}
#delete, if above does not apply
print(paste("Dataset version:", Dataset_version, sep = " "))
```

```{r echo=FALSE}
print(paste("Date:", Sys.Date()))
```
```{r echo=FALSE}
version$version.string
```
### 1. Summary: 
[*briefly describe what you are planning to do here*]

#### 2.1 Loading Libraries
[...]
#### 2.2 Loading source data  
[...]

**Comment by dblana** [comment]
I think that's a great idea! Even if people don't want to use it exactly as it is, it would be a great starting point, especially for Rmarkdown beginners 👍

**Comment by BScheliga** [comment]
I will upload something short and sweet later

**Comment by dblana** [comment]
@BScheliga your template is still there, I just renamed it: https://github.com/AbdnCHDS/guidebook/blob/master/R/Template_R_Notebook.Rmd

**Comment by BScheliga** [comment]
@dblana thank you. What do we do now with it :)

**Comment by dblana** [comment]
Link added from guidebook, we can review later on!
