### ISSUE TITLE
Please don't store your data locally!

### ISSUE THREAD

**Issue by BScheliga** [AbdnCHDS/guidebook#33]
https://github.com/AbdnCHDS/guidebook/blob/ce1ad9bf33fe3591bff49911e711fbeffea66b1e/02-Getting-Started.Rmd#L69

Put links in to DS as PHD-student and PI

https://uoa.freshservice.com/support/catalog/items/157

https://www.abdn.ac.uk/staffnet/working-here/it-services/datastorage.php#panel2066   PI

https://www.abdn.ac.uk/it/service-portfolio/sc-pc-filestore.php further information PGR -students

**Comment by ClaraGlocke** [comment]
@BScheliga Bernhard please see the branch on storing your data and issue #30 which links to this before proceeding any further or there could be duplication.  Thanks :-)

**Comment by BScheliga** [comment]
@ClaraGlocke thank you. I moved some of the information into #30. However, I will leave this open. So we remember to delete the quoted sentences.

**Comment by dblana** [comment]
@BScheliga are you happy with the [data storage chapter](https://github.com/AbdnCHDS/guidebook/blob/master/pages/data-storage.md) now or do we need to keep this issue open? (I'm doing a bit of cleaning 😄)

**Comment by BScheliga** [comment]
@dblana I added the missing links and will close this issue
